/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_org_opencv_samples_fd_DetectionBasedTracker
#define _Included_org_opencv_samples_fd_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_fr_ens_di_willow_glasspainting_QueryActivity_detect(JNIEnv*, jclass, jlong);
JNIEXPORT jint JNICALL Java_fr_ens_di_willow_glasspainting_QueryActivity_rank(JNIEnv*, jclass, jlong, jlongArray);
JNIEXPORT void JNICALL Java_fr_ens_di_willow_glasspainting_QueryActivity_load(JNIEnv*, jclass, jlongArray);
JNIEXPORT jint JNICALL Java_fr_ens_di_willow_glasspainting_QueryActivity_rank2(JNIEnv*, jclass, jlong, jlong, jlongArray, jlong, jlong);
JNIEXPORT jlong JNICALL Java_fr_ens_di_willow_glasspainting_QueryActivity_load2(JNIEnv*, jclass, jlong, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
